- name: Test firewall module (dry run)
  hosts: windows
  gather_facts: false
  tasks:
    - name: Preview inbound firewall changes
      pcs.windows.firewall_rule_state:
        group:
          - name: "@FirewallAPI.dll,*"
            enabled: false
          - name: "File and Printer Sharing*"
            enabled: false
        rule:
          - name: "Windows Remote Management (HTTP-In)"
            enabled: true
      check_mode: true
      register: fw_preview

    - name: Show planned changes
      debug:
        var: fw_preview.affected_rules
